### ISSUE TITLE
Leave——成都华栖云 | 以写作调身心

### ISSUE THREAD

**Issue by OctopusLian** [OctopusLian/octopuslian.github.io#251]
https://octopuslian.github.io/2020/12/10/leave-china-sichuan-chengdu-chinamcloud/ 

 很多事情我无法改变，但可以选择离开。 ————题记成都华栖云是我从成都飞鱼离职后入职的一家传统互联网型公司，主要面向的客户是国企和学校。从大学毕业到现在的两年内，我在这家公司不断积累社会经验，也解开了我大学时曾有过的困惑。困惑一_为什么产品经常会和研发打架？这个困惑最先来自于大学看到的段子，直到毕业后我才真实体会到这里面的心酸和无奈。2019年夏天，我记得非常清楚，已经数不清多少次，想骂我部门的W

**Comment by ch206265** [comment]
加油，可以在下份工作之前好好体验体验久违的生活！

**Comment by OctopusLian** [comment]
> @ch206265
> 加油，可以在下份工作之前好好体验体验久违的生活！

好的，谢谢！

**Comment by aladdinding** [comment]
瞎逛来到了这里 毕业一年 看完感同身受

**Comment by OctopusLian** [comment]
> @aladdinding
> 瞎逛来到了这里 毕业一年 看完感同身受

羡慕，我毕业两年，有机会交流技术呀！我之前一直在博客园写作，觉得有些局限，于是自己搭建了这个，嘿嘿^0^

**Comment by qq171987465** [comment]
哥们，我是对事不对人啊，代码写的烂还不让说了哈？？？你的centerserver现在又出问题啦，而且是我在改，惊不惊喜。

**Comment by qq171987465** [comment]
我是没见过，到处裸写SQL的，一个函数30多个参数的。哥们，真的找找自己的原因，别总抱怨别人

**Comment by OctopusLian** [comment]
> 哥们，我是对事不对人啊，代码写的烂还不让说了哈？？？你的centerserver现在又出问题啦，而且是我在改，惊不惊喜。

首先，谢谢你指出我写的服务有问题，让我有机会说下我的感受。  
我也是对事不对人：  
- 1，在我离职前一年centerserver就没有做改动，一年前就由其他同事接手；  
- 2，2019年我确实在维护centerserver，但当时接手很多其他人写的程序要做且经常加班，所以我确实没有空管centerserver的代码质量；  
- 3，`sbh`离职后一个月他的服务也出了问题，你们也要怪他，我离职后5个月你给我发消息说服务有问题，首先你确定这是我写的吗？其次就算是我写的，做研发出问题解决它本来就是一件正常不过的事（再说我这不是一走就出问题，是走了接近半年出问题），我觉得没必要把屎盆子扣在一个已经离职的身上吧。  
- 4，之前嘲笑过`wj`写的代码low，吐槽过`ysh`的for循环，还有`sbh`的内存泄漏，但你有没有想过如果最开始就做`codereview`机制，你也不至于现在这么吐槽吧，至少我曾经的导师`yfy`是这样认同的；
- 最后，如果是我的锅，我对我写的代码表示抱歉，辛苦你了^_^

**Comment by OctopusLian** [comment]
> 我是没见过，到处裸写SQL的，一个函数30多个参数的。哥们，真的找找自己的原因，别总抱怨别人

- 1，所有SQL我都是参考最开始人写的模型做的；  
- 2，我离职前一年就没有再看过和更新过centerserver的代码；  
- 3，抱怨归抱怨，这是我的自由和权利，但我抱怨完会继续前行；
- 4，就这样

**Comment by qq171987465** [comment]
> > 哥们，我是对事不对人啊，代码写的烂还不让说了哈？？？你的centerserver现在又出问题啦，而且是我在改，惊不惊喜。
> 
> 首先，谢谢你指出我写的服务有问题，让我有机会说下我的感受。
> 我也是对事不对人：
> 
> * 1，在我离职前一年centerserver就没有做改动，一年前就由其他同事接手；
> * 2，2019年我确实在维护centerserver，但当时接手很多其他人写的程序要做且经常加班，所以我确实没有空管centerserver的代码质量；
> * 3，`sbh`离职后一个月他的服务也出了问题，你们也要怪他，我离职后5个月你给我发消息说服务有问题，首先你确定这是我写的吗？其次就算是我写的，做研发出问题解决它本来就是一件正常不过的事（再说我这不是一走就出问题，是走了接近半年出问题），我觉得没必要把屎盆子扣在一个已经离职的身上吧。
> * 4，之前嘲笑过`wj`写的代码low，吐槽过`ysh`的for循环，还有`sbh`的内存泄漏，但你有没有想过如果最开始就做`codereview`机制，你也不至于现在这么吐槽吧，至少我曾经的导师`yfy`是这样认同的；
> * 最后，如果是我的锅，我对我写的代码表示抱歉，辛苦你了^_^

dsf

> > 哥们，我是对事不对人啊，代码写的烂还不让说了哈？？？你的centerserver现在又出问题啦，而且是我在改，惊不惊喜。
> 
> 首先，谢谢你指出我写的服务有问题，让我有机会说下我的感受。
> 我也是对事不对人：
> 
> * 1，在我离职前一年centerserver就没有做改动，一年前就由其他同事接手；
> * 2，2019年我确实在维护centerserver，但当时接手很多其他人写的程序要做且经常加班，所以我确实没有空管centerserver的代码质量；
> * 3，`sbh`离职后一个月他的服务也出了问题，你们也要怪他，我离职后5个月你给我发消息说服务有问题，首先你确定这是我写的吗？其次就算是我写的，做研发出问题解决它本来就是一件正常不过的事（再说我这不是一走就出问题，是走了接近半年出问题），我觉得没必要把屎盆子扣在一个已经离职的身上吧。
> * 4，之前嘲笑过`wj`写的代码low，吐槽过`ysh`的for循环，还有`sbh`的内存泄漏，但你有没有想过如果最开始就做`codereview`机制，你也不至于现在这么吐槽吧，至少我曾经的导师`yfy`是这样认同的；
> * 最后，如果是我的锅，我对我写的代码表示抱歉，辛苦你了^_^


啊？又抱怨没有人codereview了？？我承认，咱们这边确实不管代码质量的，不过嘛，现在外面的公司除了大厂，谁又会去codereview呢，出了问题还不是自己背锅，我们公司还好点没有追究责任，可以随心所欲乱写，其他地方嘛，就看你的造化了。写规范点不是给别人看的，是为了让自己工作更加轻松，你以为sbh为啥天天加班，然而东西还越做越烂，天天被运维吐槽？？SQL那个东西，我承认可能是别人的锅哦，但是你有没有想过优化呢？？你已经是工作2年多的人了哦，应该有自己的想法了哦，代码复用，封装，抽象应该掌握了哦。你说你要继续前行，那么这次就应该去大厂了哦，小公司就千万别去了哦，加油你行的
